import pytest


@pytest.mark.asyncio
async def test_project_key_autogenerated(auth_client):
    client, _ = auth_client
    p = (await client.post("/projects", json={"name": "Manageme"})).json()
    assert p["key"] == "MAN"


@pytest.mark.asyncio
async def test_custom_key_and_uniqueness(auth_client):
    client, _ = auth_client
    p = (await client.post("/projects", json={"name": "Manageme", "key": "mam"})).json()
    assert p["key"] == "MAM"  # normalized to uppercase
    # second project can't reuse the key
    dup = await client.post("/projects", json={"name": "Other", "key": "MAM"})
    assert dup.status_code == 400


@pytest.mark.asyncio
async def test_keys_unique_when_autogenerated(auth_client):
    client, _ = auth_client
    a = (await client.post("/projects", json={"name": "Manageme"})).json()
    b = (await client.post("/projects", json={"name": "Mango"})).json()
    assert a["key"] == "MAN" and b["key"] != "MAN"


@pytest.mark.asyncio
async def test_task_identifiers_sequential_per_project(auth_client):
    client, _ = auth_client
    pid = (await client.post("/projects", json={"name": "Manageme", "key": "MAM"})).json()["id"]

    t1 = (await client.post("/tasks", json={"title": "one", "projectId": pid})).json()
    t2 = (await client.post("/tasks", json={"title": "two", "projectId": pid})).json()
    assert t1["identifier"] == "MAM-001" and t1["number"] == 1
    assert t2["identifier"] == "MAM-002" and t2["number"] == 2


@pytest.mark.asyncio
async def test_projectless_tasks_use_workspace_prefix(auth_client):
    client, _ = auth_client
    t1 = (await client.post("/tasks", json={"title": "loose one"})).json()
    t2 = (await client.post("/tasks", json={"title": "loose two"})).json()
    assert t1["identifier"] == "TSK-001"
    assert t2["identifier"] == "TSK-002"


@pytest.mark.asyncio
async def test_renumber_on_move_between_namespaces(auth_client):
    client, _ = auth_client
    a = (await client.post("/projects", json={"name": "Alpha", "key": "ALP"})).json()["id"]
    b = (await client.post("/projects", json={"name": "Bravo", "key": "BRV"})).json()["id"]

    # seed Bravo so its counter is ahead
    await client.post("/tasks", json={"title": "b1", "projectId": b})
    t = (await client.post("/tasks", json={"title": "movable", "projectId": a})).json()
    assert t["identifier"] == "ALP-001"

    moved = (await client.patch(f"/tasks/{t['id']}", json={"projectId": b})).json()
    assert moved["identifier"] == "BRV-002"

    # move out to no project -> workspace sequence
    loose = (await client.patch(f"/tasks/{t['id']}", json={"projectId": None})).json()
    assert loose["identifier"] == "TSK-001"


@pytest.mark.asyncio
async def test_editing_project_key_updates_task_ids(auth_client):
    client, _ = auth_client
    pid = (await client.post("/projects", json={"name": "Manageme", "key": "MAM"})).json()["id"]
    tid = (await client.post("/tasks", json={"title": "x", "projectId": pid})).json()["id"]

    await client.patch(f"/projects/{pid}", json={"key": "MGM"})
    t = (await client.get(f"/tasks/{tid}")).json()
    assert t["identifier"] == "MGM-001"
